# Generated by Django 4.1.4 on 2023-02-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_securitate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ESP_PIR',
            new_name='PIR',
        ),
    ]
