# Generated by Django 3.2.15 on 2023-03-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_securitate', '0002_rename_esp_pir_pir'),
    ]

    operations = [
        migrations.CreateModel(
            name='DHT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=20)),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('timestamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='USA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=20)),
                ('value', models.IntegerField()),
                ('timestamp', models.DateField()),
            ],
        ),
    ]
