# Generated by Django 3.2.15 on 2023-03-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_securitate', '0003_dht_usa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pir',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usa',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
