# Generated by Django 3.2.15 on 2023-04-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_securitate', '0005_auto_20230405_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='dht',
            name='name',
            field=models.CharField(default='Temperatura si umiditate', max_length=50),
        ),
        migrations.AddField(
            model_name='pir',
            name='name',
            field=models.CharField(default='Senzor miscare', max_length=50),
        ),
        migrations.AddField(
            model_name='usa',
            name='name',
            field=models.CharField(default='Senzor usa/geam', max_length=50),
        ),
    ]
