# Generated by Django 3.2.15 on 2023-04-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_securitate', '0006_auto_20230405_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='UID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('user', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='dht',
            name='uid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pir',
            name='uid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usa',
            name='uid',
            field=models.IntegerField(default=0),
        ),
    ]
