# Generated by Django 3.2.15 on 2023-07-26 16:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('server_securitate', '0008_camera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('user', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='camera',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dht',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pir',
            name='user',
        ),
        migrations.RemoveField(
            model_name='uid',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usa',
            name='user',
        ),
        migrations.AlterField(
            model_name='camera',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 16, 27, 30, 420512, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dht',
            name='humidity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='dht',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='dht',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 16, 27, 30, 420293, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pir',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 16, 27, 30, 419728, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pir',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usa',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 16, 27, 30, 420076, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usa',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
