# Generated by Django 3.2.15 on 2023-07-26 16:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('server_securitate', '0010_auto_20230726_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 16, 28, 5, 381782, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dht',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 16, 28, 5, 381578, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pir',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 16, 28, 5, 381056, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usa',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 16, 28, 5, 381354, tzinfo=utc)),
        ),
    ]
