# Generated by Django 3.2.15 on 2023-07-29 15:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('server_securitate', '0012_auto_20230726_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('user', models.CharField(default='', max_length=60)),
                ('from_user', models.CharField(default='', max_length=60)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2023, 7, 29, 15, 51, 46, 237316, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='camera',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 15, 51, 46, 236813, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dht',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 15, 51, 46, 236527, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pir',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 15, 51, 46, 236002, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usa',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 15, 51, 46, 236308, tzinfo=utc)),
        ),
    ]
