# Generated by Django 3.2.15 on 2023-08-23 16:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('server_securitate', '0017_auto_20230823_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 16, 59, 48, 425006, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dht',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 16, 59, 48, 424799, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pir',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 16, 59, 48, 424272, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requests',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 16, 59, 48, 425629, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usa',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 16, 59, 48, 424584, tzinfo=utc)),
        ),
    ]
