# Generated by Django 3.2.15 on 2023-11-11 17:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('server_securitate', '0018_auto_20230823_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='uid',
            name='uid',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='camera',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 17, 35, 50, 180542, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='camera',
            name='uid',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='connections',
            name='uid',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='dht',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 17, 35, 50, 180322, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dht',
            name='uid',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='pir',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 17, 35, 50, 179743, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pir',
            name='uid',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='requests',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 17, 35, 50, 181096, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requests',
            name='uid',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='usa',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 17, 35, 50, 180092, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usa',
            name='uid',
            field=models.CharField(default=0, max_length=16),
        ),
    ]
