# Generated by Django 3.2.15 on 2023-11-11 17:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('server_securitate', '0019_auto_20231111_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 17, 36, 16, 402428, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dht',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 17, 36, 16, 402206, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pir',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 17, 36, 16, 401665, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requests',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 17, 36, 16, 402931, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usa',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 17, 36, 16, 401903, tzinfo=utc)),
        ),
    ]
