# Generated by Django 4.2.11 on 2024-04-24 15:36

import datetime
from django.db import migrations, models
import server_securitate.models


class Migration(migrations.Migration):

    dependencies = [
        ('server_securitate', '0020_auto_20231111_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=0, max_length=16)),
                ('image', models.ImageField(blank=True, null=True, upload_to=server_securitate.models.get_image_path)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2024, 4, 24, 15, 36, 54, 615032, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.AlterField(
            model_name='camera',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 15, 36, 54, 612244, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='dht',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 15, 36, 54, 611657, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pir',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 15, 36, 54, 610523, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='requests',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 15, 36, 54, 613779, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usa',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 15, 36, 54, 611063, tzinfo=datetime.timezone.utc)),
        ),
    ]
